* added possibly ill-fated option to run tasks optonally async moved installer to bin

diff --git a/test/10-run-inotifywait/run-test b/test/10-run-inotifywait/run-test
--- a/test/10-run-inotifywait/run-test
+++ b/test/10-run-inotifywait/run-test
@@ -1,6 +1,6 @@
 #! /usr/bin/env bash
 
-[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
+[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
 
 run_mulle_monitor()
@@ -39,8 +39,6 @@ expect_failure_mulle_monitor()
    if result="`run_mulle_monitor "$@"`"
    then
       fail "Did not fail unexpectedly"
-   else
-      log_info "Failed as expected"
    fi
 }
 
@@ -51,39 +49,26 @@ main()
 
    _options_mini_main "$@"
 
+   case "${MULLE_UNAME}" in
+     linux)
+     ;;
+
+    *)
+        log_info "skip inotifytest test on \"${MULLE_UNAME}\""
+        return 0
+     ;;
+   esac
+
    #-----------
 
-   expect_mulle_monitor ".mulle-monitor/libexec/foo-task.sh" -e task locate foo
+   INOTIFYWAIT="${PWD}/../mock-inotifywait"
+   [ -x "${INOTIFYWAIT}" ] || fail "\"${INOTIFYWAIT}\" is missing"
+   export INOTIFYWAIT
+
+   MULLE_INOTIFYWAIT_REPLAY_FILE="create-src-foo-sh-replay.txt" \
+      expect_mulle_monitor "VfL Bochum 1848" -e run
 
    log_verbose "----- #1 PASSED -----"
-
-   #-----------
-
-   expect_mulle_monitor ".mulle-monitor/libexec/bar-task.sh" -e task locate bar
-
-   log_verbose "----- #2 PASSED -----"
-
-   #-----------
-
-   expect_failure_mulle_monitor -e task locate baz
-
-   log_verbose "----- #3 PASSED -----"
-
-   #-----------
-
-   expect_mulle_monitor "" -e task test foo
-
-   log_verbose "----- #4 PASSED -----"
-
-   #-----------
-
-   expect_failure_mulle_monitor -e task test bar
-
-   log_verbose "----- #5 PASSED -----"
-
-   #-----------
-
-
 
    log_info "----- ALL PASSED -----"
 }
