adapt to changes in mulle-bashfunctions

diff --git a/mulle-monitor b/mulle-monitor
--- a/mulle-monitor
+++ b/mulle-monitor
@@ -466,6 +466,12 @@ main()
 ###
 ### INIT
 ###
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    # mingw stuff
@@ -484,16 +490,15 @@ _init()
          then
              echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
          else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
+            _fatal "Could not find libexec of mulle-bashfunctions-env"
          fi
          exit 1
       fi
    fi
 
       # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
-      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
-
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || \
+      _fatal "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
    if [ -z "${MULLE_MONITOR_LIBEXEC_DIR}" ]
    then
       r_get_libexec_dir "${MULLE_EXECUTABLE}" "mulle-monitor" "mulle-monitor-run.sh"
