* uses mulle-bashfunctions 4 now * can now run under zsh if bash is not available

diff --git a/test/05-task/run-test b/test/05-task/run-test
--- a/test/05-task/run-test
+++ b/test/05-task/run-test
@@ -2,14 +2,17 @@
 
 [ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
-
 run_mulle_monitor()
 {
    echo "####################################" >&2
    echo mulle-monitor ${MULLE_MONITOR_FLAGS} "$@"  >&2
    echo "####################################" >&2
 
-   "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@" || fail "\`mulle-monitor $*\` failed"
+   (
+      MULLE_MONITOR_LIBEXEC_DIR="`${MULLE_MONITOR} libexec-dir`"
+
+      . "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@"
+   )
 }
 
 
@@ -21,7 +24,7 @@ expect_mulle_monitor()
 
    local result
 
-   result="`run_mulle_monitor "$@"`" || exit 1
+   result="`run_mulle_monitor "$@"`" || fail "Failed unexpectedly"
 
    if [ "${result}" != "${expected}" ]
    then
@@ -49,7 +52,7 @@ main()
 {
    MULLE_MONITOR_FLAGS="$@"
 
-   _options_mini_main "$@"
+   _options_mini_main "$@" && set -x
 
    #-----------
 
